In [3]:
import pandas as pd 
import numpy as np

pd.set_option('display.max_columns',100)

In [4]:
df = pd.read_pickle('../data/lending_club_clean_base.pkl')
print(df.shape)
df.head()

(1340973, 83)

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,purpose,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,last_credit_pull_d,collections_12_mths_ex_med,application_type,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_inq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,disbursement_method,debt_settlement_flag,default_flag
100,30000,30000,30000.0,36 months,22.35,1151.16,D,D5,Supervisor,5 years,MORTGAGE,100000.0,Source Verified,Dec-2018,debt_consolidation,CA,30.46,0.0,Jan-2012,0.0,11.0,1.0,15603,37.0,19.0,w,0.0,0.0,30026.442500,30026.44,30000.0,26.44,0.0,0.0,0.0,Jan-2019,30082.32,Jan-2019,0.0,Joint App,0.0,0.0,472330.0,42200.0,4.0,42939.0,15181.0,46.9,0.0,0.0,83.0,73.0,23.0,2.0,1.0,23.0,8.0,0.0,3.0,4.0,3.0,5.0,10.0,6.0,8.0,4.0,11.0,0.0,0.0,0.0,2.0,89.5,33.3,1.0,0.0,527120.0,98453.0,28600.0,101984.0,N,Cash,N,0
152,40000,40000,40000.0,60 months,16.14,975.71,C,C4,Assistant to the Treasurer (Payroll),< 1 year,MORTGAGE,45000.0,Verified,Dec-2018,credit_card,OH,50.53,0.0,Jun-2009,0.0,18.0,0.0,34971,64.5,37.0,w,0.0,0.0,40856.678960,40856.68,40000.0,856.68,0.0,0.0,0.0,Feb-2019,40910.48,Feb-2019,0.0,Joint App,0.0,0.0,271068.0,54200.0,5.0,15059.0,14930.0,67.3,0.0,0.0,114.0,70.0,2.0,2.0,1.0,2.0,9.0,0.0,7.0,9.0,7.0,7.0,26.0,9.0,10.0,9.0,18.0,0.0,0.0,0.0,4.0,100.0,42.9,0.0,0.0,344802.0,161720.0,45700.0,167965.0,N,Cash,N,0
170,20000,20000,20000.0,36 months,7.56,622.68,A,A3,Teacher,10+ years,MORTGAGE,100000.0,Not Verified,Dec-2018,credit_card,WA,18.92,0.0,Feb-1999,0.0,9.0,0.0,25416,29.9,19.0,w,0.0,0.0,20215.792430,20215.79,20000.0,215.79,0.0,0.0,0.0,Feb-2019,20228.39,Feb-2019,0.0,Joint App,0.0,0.0,515779.0,85100.0,5.0,57309.0,59684.0,29.9,0.0,0.0,171.0,238.0,1.0,1.0,5.0,1.0,13.0,0.0,5.0,5.0,5.0,6.0,5.0,5.0,9.0,5.0,9.0,0.0,0.0,0.0,1.0,94.7,20.0,0.0,0.0,622183.0,71569.0,85100.0,74833.0,N,Cash,N,0
186,4500,4500,4500.0,36 months,11.31,147.99,B,B3,Accounts Examiner III,10+ years,RENT,38500.0,Not Verified,Dec-2018,credit_card,TX,4.64,0.0,Dec-2003,0.0,12.0,0.0,4472,15.3,25.0,w,0.0,0.0,4549.217149,4549.22,4500.0,49.22,0.0,0.0,0.0,Feb-2019,4553.46,Feb-2019,0.0,Individual,0.0,306.0,29137.0,29200.0,8.0,2428.0,10735.0,28.9,0.0,0.0,180.0,69.0,2.0,2.0,0.0,2.0,6.0,1.0,3.0,5.0,5.0,6.0,10.0,11.0,15.0,5.0,12.0,0.0,0.0,0.0,4.0,91.7,0.0,0.0,0.0,53795.0,29137.0,15100.0,24595.0,N,Cash,N,0
215,8425,8425,8425.0,36 months,27.27,345.18,E,E5,Senior Director Risk Management,3 years,MORTGAGE,450000.0,Verified,Dec-2018,credit_card,MA,12.37,0.0,Oct-1997,0.0,21.0,0.0,36812,65.7,37.0,w,0.0,0.0,8735.148975,8735.15,8425.0,310.15,0.0,0.0,0.0,Feb-2019,8754.30,Feb-2019,0.0,Joint App,0.0,0.0,690320.0,56000.0,10.0,34516.0,11632.0,74.6,0.0,0.0,254.0,89.0,12.0,12.0,4.0,18.0,4.0,0.0,6.0,8.0,8.0,10.0,16.0,13.0,17.0,8.0,21.0,0.0,0.0,0.0,2.0,100.0,50.0,0.0,0.0,768304.0,189194.0,45800.0,189054.0,N,Cash,N,0

## Cleaning Terms Columns

In [7]:
df['term'].unique()

array([' 36 months', ' 60 months'], dtype=object)

In [10]:
df['term_months']=df['term'].str.extract('(\d+)').astype(float)
df['term_months'].unique()

array([36., 60.])

## Converting emp_length to numeric value

In [22]:
Number_of_unique_emp_len=df['emp_length'].nunique()
print(f'Number of unique employment length values {Number_of_unique_emp_len} \n\n')
df['emp_length'].unique()

Number of unique employment length values 11

array(['5 years', '< 1 year', '10+ years', '3 years', '4 years', '1 year',
       '8 years', nan, '2 years', '6 years', '9 years', '7 years'],
      dtype=object)

emp_length_map = {
     '10+ years':10,
     '9 years': 9,
     '8 years': 8,
     '7 years': 7,
     '6 years': 6,
     '5 years': 5,
     '4 years': 4,
     '3 years': 3,
     '2 years': 2,
     '1 years': 1,
}

df['emp_length_num']=df['emp_length'].map(emp_length_map)

In [24]:
df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,purpose,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,last_credit_pull_d,collections_12_mths_ex_med,application_type,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_inq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,disbursement_method,debt_settlement_flag,default_flag,term_months,emp_length_num
100,30000,30000,30000.0,36 months,22.35,1151.16,D,D5,Supervisor,5 years,MORTGAGE,100000.0,Source Verified,Dec-2018,debt_consolidation,CA,30.46,0.0,Jan-2012,0.0,11.0,1.0,15603,37.0,19.0,w,0.0,0.0,30026.442500,30026.44,30000.0,26.44,0.0,0.0,0.0,Jan-2019,30082.32,Jan-2019,0.0,Joint App,0.0,0.0,472330.0,42200.0,4.0,42939.0,15181.0,46.9,0.0,0.0,83.0,73.0,23.0,2.0,1.0,23.0,8.0,0.0,3.0,4.0,3.0,5.0,10.0,6.0,8.0,4.0,11.0,0.0,0.0,0.0,2.0,89.5,33.3,1.0,0.0,527120.0,98453.0,28600.0,101984.0,N,Cash,N,0,36.0,5.0
152,40000,40000,40000.0,60 months,16.14,975.71,C,C4,Assistant to the Treasurer (Payroll),< 1 year,MORTGAGE,45000.0,Verified,Dec-2018,credit_card,OH,50.53,0.0,Jun-2009,0.0,18.0,0.0,34971,64.5,37.0,w,0.0,0.0,40856.678960,40856.68,40000.0,856.68,0.0,0.0,0.0,Feb-2019,40910.48,Feb-2019,0.0,Joint App,0.0,0.0,271068.0,54200.0,5.0,15059.0,14930.0,67.3,0.0,0.0,114.0,70.0,2.0,2.0,1.0,2.0,9.0,0.0,7.0,9.0,7.0,7.0,26.0,9.0,10.0,9.0,18.0,0.0,0.0,0.0,4.0,100.0,42.9,0.0,0.0,344802.0,161720.0,45700.0,167965.0,N,Cash,N,0,60.0,NaN
170,20000,20000,20000.0,36 months,7.56,622.68,A,A3,Teacher,10+ years,MORTGAGE,100000.0,Not Verified,Dec-2018,credit_card,WA,18.92,0.0,Feb-1999,0.0,9.0,0.0,25416,29.9,19.0,w,0.0,0.0,20215.792430,20215.79,20000.0,215.79,0.0,0.0,0.0,Feb-2019,20228.39,Feb-2019,0.0,Joint App,0.0,0.0,515779.0,85100.0,5.0,57309.0,59684.0,29.9,0.0,0.0,171.0,238.0,1.0,1.0,5.0,1.0,13.0,0.0,5.0,5.0,5.0,6.0,5.0,5.0,9.0,5.0,9.0,0.0,0.0,0.0,1.0,94.7,20.0,0.0,0.0,622183.0,71569.0,85100.0,74833.0,N,Cash,N,0,36.0,10.0
186,4500,4500,4500.0,36 months,11.31,147.99,B,B3,Accounts Examiner III,10+ years,RENT,38500.0,Not Verified,Dec-2018,credit_card,TX,4.64,0.0,Dec-2003,0.0,12.0,0.0,4472,15.3,25.0,w,0.0,0.0,4549.217149,4549.22,4500.0,49.22,0.0,0.0,0.0,Feb-2019,4553.46,Feb-2019,0.0,Individual,0.0,306.0,29137.0,29200.0,8.0,2428.0,10735.0,28.9,0.0,0.0,180.0,69.0,2.0,2.0,0.0,2.0,6.0,1.0,3.0,5.0,5.0,6.0,10.0,11.0,15.0,5.0,12.0,0.0,0.0,0.0,4.0,91.7,0.0,0.0,0.0,53795.0,29137.0,15100.0,24595.0,N,Cash,N,0,36.0,10.0
215,8425,8425,8425.0,36 months,27.27,345.18,E,E5,Senior Director Risk Management,3 years,MORTGAGE,450000.0,Verified,Dec-2018,credit_card,MA,12.37,0.0,Oct-1997,0.0,21.0,0.0,36812,65.7,37.0,w,0.0,0.0,8735.148975,8735.15,8425.0,310.15,0.0,0.0,0.0,Feb-2019,8754.30,Feb-2019,0.0,Joint App,0.0,0.0,690320.0,56000.0,10.0,34516.0,11632.0,74.6,0.0,0.0,254.0,89.0,12.0,12.0,4.0,18.0,4.0,0.0,6.0,8.0,8.0,10.0,16.0,13.0,17.0,8.0,21.0,0.0,0.0,0.0,2.0,100.0,50.0,0.0,0.0,768304.0,189194.0,45800.0,189054.0,N,Cash,N,0,36.0,3.0

## Convert Date Columns

In [27]:
date_cols = ["issue_d", "earliest_cr_line", "last_pymnt_d", "last_credit_pull_d"]
df[date_cols].head()

      issue_d earliest_cr_line last_pymnt_d last_credit_pull_d
100  Dec-2018         Jan-2012     Jan-2019           Jan-2019
152  Dec-2018         Jun-2009     Feb-2019           Feb-2019
170  Dec-2018         Feb-1999     Feb-2019           Feb-2019
186  Dec-2018         Dec-2003     Feb-2019           Feb-2019
215  Dec-2018         Oct-1997     Feb-2019           Feb-2019

In [28]:
for col in date_cols:
    if col in df:
        df[col] = pd.to_datetime(df[col],format='%b-%Y',errors='coerce')

df[date_cols].head(10)

       issue_d earliest_cr_line last_pymnt_d last_credit_pull_d
100 2018-12-01       2012-01-01   2019-01-01         2019-01-01
152 2018-12-01       2009-06-01   2019-02-01         2019-02-01
170 2018-12-01       1999-02-01   2019-02-01         2019-02-01
186 2018-12-01       2003-12-01   2019-02-01         2019-02-01
215 2018-12-01       1997-10-01   2019-02-01         2019-02-01
269 2018-12-01       1995-04-01   2019-01-01         2019-01-01
271 2018-12-01       2009-04-01   2019-01-01         2019-02-01
296 2018-12-01       2004-03-01   2019-01-01         2019-01-01
369 2018-12-01       2007-06-01   2019-02-01         2019-01-01
379 2018-12-01       2002-10-01   2019-01-01         2019-02-01

In [29]:
## Create Date Derived features

In [34]:
df['issue_month']=df['issue_d'].dt.month
df['issue_year']=df['issue_d'].dt.year

df['credit_history_months']= ((df['issue_d'].dt.year - df['earliest_cr_line'].dt.year) * 12) - (df['issue_d'].dt.month - df['earliest_cr_line'].dt.month)
#Invalid credit_history_months set to missing
df.loc[df['credit_history_months']<0,'credit_history_months']=np.nan


df[date_cols + ['issue_month', 'issue_year', 'credit_history_months']].head()

,issue_d,earliest_cr_line,last_pymnt_d,last_credit_pull_d,issue_month,issue_year,credit_history_months
100,2018-12-01,2012-01-01,2019-01-01,2019-01-01,12,2018,61.0
152,2018-12-01,2009-06-01,2019-02-01,2019-02-01,12,2018,102.0
170,2018-12-01,1999-02-01,2019-02-01,2019-02-01,12,2018,218.0
186,2018-12-01,2003-12-01,2019-02-01,2019-02-01,12,2018,180.0
215,2018-12-01,1997-10-01,2019-02-01,2019-02-01,12,2018,250.0

In [35]:
df[df['credit_history_months']<0]

Empty DataFrame
Columns: [loan_amnt, funded_amnt, funded_amnt_inv, term, int_rate, installment, grade, sub_grade, emp_title, emp_length, home_ownership, annual_inc, verification_status, issue_d, purpose, addr_state, dti, delinq_2yrs, earliest_cr_line, inq_last_6mths, open_acc, pub_rec, revol_bal, revol_util, total_acc, initial_list_status, out_prncp, out_prncp_inv, total_pymnt, total_pymnt_inv, total_rec_prncp, total_rec_int, total_rec_late_fee, recoveries, collection_recovery_fee, last_pymnt_d, last_pymnt_amnt, last_credit_pull_d, collections_12_mths_ex_med, application_type, acc_now_delinq, tot_coll_amt, tot_cur_bal, total_rev_hi_lim, acc_open_past_24mths, avg_cur_bal, bc_open_to_buy, bc_util, chargeoff_within_12_mths, delinq_amnt, mo_sin_old_il_acct, mo_sin_old_rev_tl_op, mo_sin_rcnt_rev_tl_op, mo_sin_rcnt_tl, mort_acc, mths_since_recent_bc, mths_since_recent_inq, num_accts_ever_120_pd, num_actv_bc_tl, num_actv_rev_tl, num_bc_sats, num_bc_tl, num_il_tl, num_op_rev_tl, num_rev_accts, num_rev_tl_bal_gt_0, num_sats, num_tl_120dpd_2m, num_tl_30dpd, num_tl_90g_dpd_24m, num_tl_op_past_12m, pct_tl_nvr_dlq, percent_bc_gt_75, pub_rec_bankruptcies, tax_liens, tot_hi_cred_lim, total_bal_ex_mort, total_bc_limit, total_il_high_credit_limit, hardship_flag, disbursement_method, debt_settlement_flag, default_flag, term_months, emp_length_num, issue_month, issue_year, credit_history_months]
Index: []

### Data Checks & Preperation before Creating Ratio Columns

#### Denominator quality check before creating ratios

In [40]:
print(f"Number of NULLs in annual_inc {df['annual_inc'].isnull().sum()}")
print(f"Number of NULLs in total_acc {df['total_acc'].isnull().sum()}")
print(f"Number of NULLs in funded_amnt {df['funded_amnt'].isnull().sum()}")

Number of NULLs in annual_inc 4
Number of NULLs in total_acc 29
Number of NULLs in funded_amnt 0

In [42]:
print(f"Number of negatives in annual_inc {(df['annual_inc']<= 0).sum()}")
print(f"Number of negatives in total_acc {(df['total_acc']<= 0).sum()}")
print(f"Number of negatives in funded_amnt {(df['funded_amnt']<= 0).sum()}")

Number of negatives in annual_inc 343
Number of negatives in total_acc 0
Number of negatives in funded_amnt 0

#### Clean Denominator Columns

In [48]:
df['annual_inc_clean']=df['annual_inc'].where(df['annual_inc']>0, np.nan)
df['total_acc_clean']=df['total_acc'].where(df['total_acc']>0, np.nan)
df['funded_amnt_clean']=df['funded_amnt'].where(df['funded_amnt']>0, np.nan)

In [49]:
print(f"Number of invalid in annual_inc_clean {(df['annual_inc_clean']<= 0).sum()}")
print(f"Number of invalid in total_acc_clean {(df['total_acc_clean']<= 0).sum()}")
print(f"Number of invalid in funded_amnt_clean {(df['funded_amnt_clean']<= 0).sum()}")

Number of invalid in annual_inc_clean 0
Number of invalid in total_acc_clean 0
Number of invalid in funded_amnt_clean 0

## Financial Health Using Ratios/ Repayment Capacity Feature

In [50]:
df.columns

Index(['loan_amnt', 'funded_amnt', 'funded_amnt_inv', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'emp_title', 'emp_length',
       'home_ownership', 'annual_inc', 'verification_status', 'issue_d',
       'purpose', 'addr_state', 'dti', 'delinq_2yrs', 'earliest_cr_line',
       'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal', 'revol_util',
       'total_acc', 'initial_list_status', 'out_prncp', 'out_prncp_inv',
       'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_d', 'last_pymnt_amnt', 'last_credit_pull_d',
       'collections_12_mths_ex_med', 'application_type', 'acc_now_delinq',
       'tot_coll_amt', 'tot_cur_bal', 'total_rev_hi_lim',
       'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_inq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m',
       'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m',
       'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'pub_rec_bankruptcies',
       'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit', 'hardship_flag', 'disbursement_method',
       'debt_settlement_flag', 'default_flag', 'term_months', 'emp_length_num',
       'issue_month', 'issue_year', 'credit_history_months',
       'annual_inc_clean', 'total_acc_clean', 'funded_amnt_clean'],
      dtype='object')

In [51]:
df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,purpose,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,last_credit_pull_d,collections_12_mths_ex_med,application_type,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_inq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,disbursement_method,debt_settlement_flag,default_flag,term_months,emp_length_num,issue_month,issue_year,credit_history_months,annual_inc_clean,total_acc_clean,funded_amnt_clean
100,30000,30000,30000.0,36 months,22.35,1151.16,D,D5,Supervisor,5 years,MORTGAGE,100000.0,Source Verified,2018-12-01,debt_consolidation,CA,30.46,0.0,2012-01-01,0.0,11.0,1.0,15603,37.0,19.0,w,0.0,0.0,30026.442500,30026.44,30000.0,26.44,0.0,0.0,0.0,2019-01-01,30082.32,2019-01-01,0.0,Joint App,0.0,0.0,472330.0,42200.0,4.0,42939.0,15181.0,46.9,0.0,0.0,83.0,73.0,23.0,2.0,1.0,23.0,8.0,0.0,3.0,4.0,3.0,5.0,10.0,6.0,8.0,4.0,11.0,0.0,0.0,0.0,2.0,89.5,33.3,1.0,0.0,527120.0,98453.0,28600.0,101984.0,N,Cash,N,0,36.0,5.0,12,2018,61.0,100000.0,19.0,30000
152,40000,40000,40000.0,60 months,16.14,975.71,C,C4,Assistant to the Treasurer (Payroll),< 1 year,MORTGAGE,45000.0,Verified,2018-12-01,credit_card,OH,50.53,0.0,2009-06-01,0.0,18.0,0.0,34971,64.5,37.0,w,0.0,0.0,40856.678960,40856.68,40000.0,856.68,0.0,0.0,0.0,2019-02-01,40910.48,2019-02-01,0.0,Joint App,0.0,0.0,271068.0,54200.0,5.0,15059.0,14930.0,67.3,0.0,0.0,114.0,70.0,2.0,2.0,1.0,2.0,9.0,0.0,7.0,9.0,7.0,7.0,26.0,9.0,10.0,9.0,18.0,0.0,0.0,0.0,4.0,100.0,42.9,0.0,0.0,344802.0,161720.0,45700.0,167965.0,N,Cash,N,0,60.0,NaN,12,2018,102.0,45000.0,37.0,40000
170,20000,20000,20000.0,36 months,7.56,622.68,A,A3,Teacher,10+ years,MORTGAGE,100000.0,Not Verified,2018-12-01,credit_card,WA,18.92,0.0,1999-02-01,0.0,9.0,0.0,25416,29.9,19.0,w,0.0,0.0,20215.792430,20215.79,20000.0,215.79,0.0,0.0,0.0,2019-02-01,20228.39,2019-02-01,0.0,Joint App,0.0,0.0,515779.0,85100.0,5.0,57309.0,59684.0,29.9,0.0,0.0,171.0,238.0,1.0,1.0,5.0,1.0,13.0,0.0,5.0,5.0,5.0,6.0,5.0,5.0,9.0,5.0,9.0,0.0,0.0,0.0,1.0,94.7,20.0,0.0,0.0,622183.0,71569.0,85100.0,74833.0,N,Cash,N,0,36.0,10.0,12,2018,218.0,100000.0,19.0,20000
186,4500,4500,4500.0,36 months,11.31,147.99,B,B3,Accounts Examiner III,10+ years,RENT,38500.0,Not Verified,2018-12-01,credit_card,TX,4.64,0.0,2003-12-01,0.0,12.0,0.0,4472,15.3,25.0,w,0.0,0.0,4549.217149,4549.22,4500.0,49.22,0.0,0.0,0.0,2019-02-01,4553.46,2019-02-01,0.0,Individual,0.0,306.0,29137.0,29200.0,8.0,2428.0,10735.0,28.9,0.0,0.0,180.0,69.0,2.0,2.0,0.0,2.0,6.0,1.0,3.0,5.0,5.0,6.0,10.0,11.0,15.0,5.0,12.0,0.0,0.0,0.0,4.0,91.7,0.0,0.0,0.0,53795.0,29137.0,15100.0,24595.0,N,Cash,N,0,36.0,10.0,12,2018,180.0,38500.0,25.0,4500
215,8425,8425,8425.0,36 months,27.27,345.18,E,E5,Senior Director Risk Management,3 years,MORTGAGE,450000.0,Verified,2018-12-01,credit_card,MA,12.37,0.0,1997-10-01,0.0,21.0,0.0,36812,65.7,37.0,w,0.0,0.0,8735.148975,8735.15,8425.0,310.15,0.0,0.0,0.0,2019-02-01,8754.30,2019-02-01,0.0,Joint App,0.0,0.0,690320.0,56000.0,10.0,34516.0,11632.0,74.6,0.0,0.0,254.0,89.0,12.0,12.0,4.0,18.0,4.0,0.0,6.0,8.0,8.0,10.0,16.0,13.0,17.0,8.0,21.0,0.0,0.0,0.0,2.0,100.0,50.0,0.0,0.0,768304.0,189194.0,45800.0,189054.0,N,Cash,N,0,36.0,3.0,12,2018,250.0,450000.0,37.0,8425

In [52]:
df['loan_to_income_ratio'] = df['loan_amnt']/df['annual_inc_clean']
df['funded_to_income_ratio']= df['funded_amnt']/df['annual_inc_clean']
df['revol_bal_to_income_ratio']=df['revol_bal']/df['annual_inc_clean']
df['installment_to_income_ratio'] = (df['installment']*12)/df['annual_inc_clean']

df[['loan_to_income_ratio', 'funded_to_income_ratio', 'revol_bal_to_income_ratio', 'installment_to_income_ratio']].head(5)

,loan_to_income_ratio,funded_to_income_ratio,revol_bal_to_income_ratio,installment_to_income_ratio
100,0.300000,0.300000,0.156030,0.138139
152,0.888889,0.888889,0.777133,0.260189
170,0.200000,0.200000,0.254160,0.074722
186,0.116883,0.116883,0.116156,0.046127
215,0.018722,0.018722,0.081804,0.009205

## Credit Utilization/ Account Activity Features

In [56]:
df['open_acc_to_total_acc_ratio'] = df['open_acc']/df['total_acc_clean']

df['dti_clean']=df['dti'].where(df['dti']>=0,np.nan)
df['revol_util_clean']=df['revol_util'].where(df['revol_util']>=0,np.nan)

df['debt_burden_score'] = df['dti_clean'] + df['revol_util_clean']

df[['open_acc_to_total_acc_ratio','dti_clean','revol_util_clean','debt_burden_score']].head()

,open_acc_to_total_acc_ratio,dti_clean,revol_util_clean,debt_burden_score
100,0.578947,30.46,37.0,67.46
152,0.486486,50.53,64.5,115.03
170,0.473684,18.92,29.9,48.82
186,0.480000,4.64,15.3,19.94
215,0.567568,12.37,65.7,78.07

## Delinquency & Risk Indicator Flags

In [58]:
df['has_delinquency'] = np.where(df['delinq_2yrs']>0,1,0)
df['has_public_record'] = np.where(df['pub_rec']>0,1,0)
df['has_bankruptcy'] = np.where(df['pub_rec_bankruptcies']>0,1,0)

df['high_revol_util_flag'] = np.where(df['revol_util_clean']>75,1,0)
df['high_dti_flag'] = np.where(df['dti_clean']>35,1,0)

df[['has_delinquency', 'has_public_record', 'has_bankruptcy', 'high_revol_util_flag', 'high_dti_flag']].head()

,has_delinquency,has_public_record,has_bankruptcy,high_revol_util_flag,high_dti_flag
100,0,1,1,0,0
152,0,0,0,0,1
170,0,0,0,0,0
186,0,0,0,0,0
215,0,0,0,0,0

## Grade Ordinal Encoding Using Map

In [60]:
df['grade'].unique()

array(['D', 'C', 'A', 'B', 'E', 'G', 'F'], dtype=object)

In [61]:
grade_map = {
    'A':1,
    'B':2,
    'C':3,
    'D':4,
    'E':5,
    'F':6,
    'G':7
}

In [63]:
df['grade_num'] = df['grade'].map(grade_map)
df[['grade', 'grade_num']]. drop_duplicates().sort_values('grade_num')

      grade  grade_num
170       A          1
186       B          2
152       C          3
100       D          4
215       E          5
51968     F          6
19102     G          7

##  Sub-grade ordinal encoding
###### eg:A1=1, A2=2, ..., G5=35

In [69]:
sorted(df['sub_grade'].unique())

['A1',
 'A2',
 'A3',
 'A4',
 'A5',
 'B1',
 'B2',
 'B3',
 'B4',
 'B5',
 'C1',
 'C2',
 'C3',
 'C4',
 'C5',
 'D1',
 'D2',
 'D3',
 'D4',
 'D5',
 'E1',
 'E2',
 'E3',
 'E4',
 'E5',
 'F1',
 'F2',
 'F3',
 'F4',
 'F5',
 'G1',
 'G2',
 'G3',
 'G4',
 'G5']

In [70]:
sub_grade_order = {
    grade: index+1
    for index, grade in enumerate(sorted(df['sub_grade'].unique()))
}

sub_grade_order

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35}

In [72]:
df['sub_grade_number'] = df['sub_grade'].map(sub_grade_order)

df[['sub_grade','sub_grade_number']].drop_duplicates().sort_values('sub_grade_number')

       sub_grade  sub_grade_number
5040          A1                 1
1715          A2                 2
170           A3                 3
379           A4                 4
1492          A5                 5
829           B1                 6
1106          B2                 7
186           B3                 8
930           B4                 9
646           B5                10
296           C1                11
1527          C2                12
1176          C3                13
152           C4                14
1876          C5                15
269           D1                16
873           D2                17
2175          D3                18
3168          D4                19
100           D5                20
402           E1                21
4040          E2                22
4022          E3                23
765           E4                24
215           E5                25
51968         F1                26
71574         F2                27
97761         F3                28
89655         F4                29
78394         F5                30
27518         G1                31
19102         G2                32
138390        G3                33
70382         G4                34
130065        G5                35